version: 2

sources:
  - name: IDMC_Source
    database: IDMC_Source
    schema: public
    tables:
      - name: IDMC_Source
        description: "Source table for m_hierarchyparser"
        columns:
          - name: FIELD1
            tests:
              - not_null
