version: 2
sources:
  - name: idmc_source_p5
    schema: public
    tables:
      - name: source_p5
        description: "Source table for m_hierarchyparser"
        columns:
          - name: FIELD1
            tests:
              - not_null
