name: 'jinjaneering_migration'
version: '1.0.0'
config-version: 2

profile: 'jinjaneering'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  load_date: "{{ run_started_at }}"
  environment: "{{ target.name }}"

models:
  jinjaneering_migration:
    +materialized: table
    +tags: ['jinjaneering']
