version: 2

sources:
  - name: IDMC_Source
    database: IDMC_Source
    schema: public
    tables:
      - name: IDMC_Source
        description: "Source table for m_AllTransformationMapping"
        columns:
          - name: employee_id
            tests:
              - not_null
          - name: first_name
            tests:
              - not_null
          - name: last_name
            tests:
              - not_null
          - name: email
            tests:
              - not_null
          - name: phone
            tests:
              - not_null
  - name: Mapplet
    database: Mapplet
    schema: public
    tables:
      - name: Mapplet
        description: "Source table for mplt_QuaterlySal"
        columns:
          - name: Salary
            tests:
              - not_null
