version: 2
sources:
  - name: idmc_source_p9
    schema: public
    tables:
      - name: source_p9
        description: "Source table for m_MacroExpression"
        columns:
          - name: EMPLOYEE_ID
            tests:
              - not_null
          - name: FIRST_NAME
            tests:
              - not_null
          - name: LAST_NAME
            tests:
              - not_null
          - name: EMAIL
            tests:
              - not_null
          - name: PHONE
            tests:
              - not_null
