version: 2

models:
  - name: complex_multi_target
    description: "Complex Multi-Target Router - Jinjaneering generated pattern model"
    config:
      tags: ['jinjaneering', 'complex_multi_target']
    columns:
      # Entity: m_SCD_Type2
    tests:
      - not_null
      - unique:
          column_name: "{{ pk_field }}"

