version: 2
sources:
  - name: idmc_source_p8
    schema: public
    tables:
      - name: source_p8
        description: "Source table for M_Mass_Ingestion"
        columns:
          - name: employee_id
            tests:
              - not_null
          - name: first_name
            tests:
              - not_null
          - name: last_name
            tests:
              - not_null
          - name: department
            tests:
              - not_null
          - name: job_title
            tests:
              - not_null
