version: 2

sources:
  - name: IDMC_Source
    database: IDMC_Source
    schema: public
    tables:
      - name: IDMC_Source
        description: "Source table for m_joiner_lkp"
        columns:
          - name: ORDER_ID
            tests:
              - not_null
          - name: CUSTOMER_ID
            tests:
              - not_null
          - name: STATUS
            tests:
              - not_null
          - name: SALESMAN_ID
            tests:
              - not_null
          - name: ORDER_DATE
            tests:
              - not_null
