version: 2
sources:
  - name: idmc_source_p1
    schema: public
    tables:
      - name: source_p1
        description: "Source table for m_joiner_lkp"
        columns:
          - name: ORDER_ID
            tests:
              - not_null
          - name: CUSTOMER_ID
            tests:
              - not_null
          - name: STATUS
            tests:
              - not_null
          - name: SALESMAN_ID
            tests:
              - not_null
          - name: ORDER_DATE
            tests:
              - not_null
