version: 2

sources:
  - name: IDMC_Source
    database: IDMC_Source
    schema: public
    tables:
      - name: IDMC_Source
        description: "Source table for M_Transactional_Control"
        columns:
          - name: ID
            tests:
              - not_null
          - name: FIRSTNAME
            tests:
              - not_null
          - name: LASTNAME
            tests:
              - not_null
          - name: HOMEPHONE
            tests:
              - not_null
          - name: CELLPHONE
            tests:
              - not_null
