version: 2
sources:
  - name: idmc_source_p6
    schema: public
    tables:
      - name: source_p6
        description: "Source table for m_Intelligent_sm"
        columns:
          - name: Path
            tests:
              - not_null
